import { NOTIFICATION_TYPES } from "./notificationTypes";

export const NOTIFICATION_ROUTES = {
  [NOTIFICATION_TYPES.ANNOUNCEMENT]: "/forum",

  // CLIENT
  [NOTIFICATION_TYPES.BOOKING_REMINDER]: "/rezervacije",
  [NOTIFICATION_TYPES.BOOKING_CANCELED_BY_ADMIN]: "/rezervacije",
  [NOTIFICATION_TYPES.SUBSCRIPTION_ASSIGNED]: "/profil/me",
  [NOTIFICATION_TYPES.SUBSCRIPTION_ENDING]: "/profil/me",
  [NOTIFICATION_TYPES.SUBSCRIPTION_ENDED]: "/profil/me",
  SUBSCRIPTION_EXPIRY: "/profil/me",
  [NOTIFICATION_TYPES.PROFILE_EDITED_BY_ADMIN]: "/profil/me",
  [NOTIFICATION_TYPES.MESSAGE_RECEIVED]: "/chat",
  CHAT_MESSAGE: "/chat",

  // ADMIN
  [NOTIFICATION_TYPES.NEW_BOOKING]: "/raspored",
  [NOTIFICATION_TYPES.BOOKING_CANCELED_BY_CLIENT]: "/raspored",
  [NOTIFICATION_TYPES.CLIENT_PROFILE_EDITED]: "/klijenti",
};
