export const NOTIFICATION_TYPES = {
  ANNOUNCEMENT: "ANNOUNCEMENT",

  // CLIENT
  BOOKING_REMINDER: "BOOKING_REMINDER",
  BOOKING_CANCELED_BY_ADMIN: "BOOKING_CANCELED_BY_ADMIN",
  SUBSCRIPTION_ASSIGNED: "SUBSCRIPTION_ASSIGNED",
  SUBSCRIPTION_ENDING: "SUBSCRIPTION_ENDING",
  SUBSCRIPTION_ENDED: "SUBSCRIPTION_ENDED",
  PROFILE_EDITED_BY_ADMIN: "PROFILE_EDITED_BY_ADMIN",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",

  // ADMIN
  NEW_BOOKING: "NEW_BOOKING",
  BOOKING_CANCELED_BY_CLIENT: "BOOKING_CANCELED_BY_CLIENT",
  CLIENT_PROFILE_EDITED: "CLIENT_PROFILE_EDITED",
};
